### ISSUE TITLE
Fix object collision so it complies with the conservation of energy

### ISSUE THREAD

**Issue by HermannBjorgvin** [HermannBjorgvin/Gravity-Experiments#1]
In the file js/gravity/modules/spacetime.js you can find a snippet of code that joins objects if they are close enough to eachother. This can be improved in various ways but one is to fix the wrong math that I used. When two objects join they don't work within the first law of thermodynamics, which is not optimal.

I'm not sure how to fix it in a way that also maintains the gravitational potential energy as well though

50 lines from 115 and 165 in spacetime.js

``` javascript
        // Find clustering objects and join them - unfinished
        // THIS IS CURRENTLY PHYSICALLY INNACCURATE, WILL FIX SOON
        for (var a = spacetime.length - 1; a >= 0; a--) {
            var objectA = spacetime[a];

            for (var b = spacetime.length - 1; b >= 0; b--) {
                if (a !== b) {
                    var objectB = spacetime[b];

                    if (
                        pythagoras(objectA, objectB) < getObjectRadius(objectA) + getObjectRadius(objectB)
                    ){
                        var camFocus = false;
                        if(objectB.cameraFocus === true || objectA.cameraFocus === true){
                            camFocus = true;
                        }

                        // Splice the objects from 
                        spacetime = _.without(spacetime, objectA);
                        spacetime = _.without(spacetime, objectB);

                        var newMass = objectA.mass + objectB.mass;
                        var massRatio = objectA.mass/newMass;

                        var newMomentum = getMomentum(objectA) + getMomentum(objectB);
                        var momentumRatio = newMomentum/getMomentum(objectA);

                        var newDensity = objectA.density*massRatio + objectB.density*(1-massRatio);

                        var newObject = {
                            cameraFocus: camFocus,
                            x: objectA.x*getMomentum(objectA)/newMomentum + objectB.x*getMomentum(objectB)/newMomentum, // Change later
                            y: objectA.y*getMomentum(objectA)/newMomentum + objectB.y*getMomentum(objectB)/newMomentum, // Change later
                            velX: objectA.velX*objectA.mass/newMass + objectB.velX*objectB.mass/newMass, // Change later
                            velY: objectA.velY*objectA.mass/newMass + objectB.velY*objectB.mass/newMass, // Change later
                            deltaX:0, // useless info
                            deltaY:0, // useless info
                            mass: newMass, 
                            density: newDensity,
                            path: []
                        };

                        // Give the new object the larger objects previous path, looks nicer
                        var newPath = objectA.mass >= objectB.mass ? objectA.path : objectB.path;
                        newObject.path = newPath;

                        spacetime.push(newObject);
                    };
                };
            };
        };
```

**Comment by Pluckerpluck** [comment]
Not sure this is actually an issue. In a collision in which the two objects "stick" together to become one energy isn't conserved. In real life this is because energy is given off as heat and sound in the collision. Energy is used to morph the objects such that they become one.

Only if the collisions were elastic would they save energy. 

So don't worry this is correct. In collisions conserve momentum, don't get tricked by energy.

Edit: It should be fairly obvious when you look at the two equations:

mv + MV = (m+M)newV        Conservation of momentum

mv^2 + MV^2 = (m+M)newV^2          Conservation of energy

the (m+M) represents the objects sticking together. You can pretty much see that these don't work together (except when all Vs are 1).

**Comment by scchow** [comment]
What is specifically wrong with the code right now? As far as I can tell, the only part that might be wrong is that the new (x,y) position of the object should be weighted by the mass of each contributing object, as you have done with the velX and velY.

I'm not sure what you mean by conserves gravitational potential energy. Considering a two particle (circle) system, each particle pulls the other towards one another. Once they collide, there is no more gravitational potential energy since there is only one circle now.

**Comment by Pluckerpluck** [comment]
Only comment is I don't know why you use (velocity*mass) sometimes and getMomentum other times. Just a bit random.

But yeah as above position should be weighted by just mass, not momentum.

**Comment by HermannBjorgvin** [comment]
Yeah, I was thinking about it wrong, I should have been thinking about it like finding the new center of mass and joining the momentum of the two. Right?

**Comment by scchow** [comment]
Yeah that seems correct. Also something to keep in mind is that momentum is a vector, which means it has an x and y component. So you should join the x components and y components of the momentum of each respective object.

**Comment by Pluckerpluck** [comment]
Yep. Find the new centre of mass, and ensure momentum is conserved in the X and Y directions separately. Everything looks good now.

Your newMomentum variable (which I believe we're not using) technically gives you a number, it's just not very useful in calculations (because it doesn't take into account direction as scchow said).

Edit: You'll probably want to close this issue.

**Comment by HermannBjorgvin** [comment]
Yes, I should clean up some of the code if other people will be looking at it. If you want to rename something btw you can just go ahead. All looks good right now anyways.
