### ISSUE TITLE
Setting calculation speed high makes calculations imprecise

### ISSUE THREAD

**Issue by Fabian42** [HermannBjorgvin/Gravity-Experiments#17]
When you set the calculation speed high (10 or 100 or so), objects don't behave the same, instead they often fling out into space where they have previously rotated regularly. The cause is probably that the calculation speed setting doesn't actually set the time between steps, but instead takes larger steps at once. This make small imprecisions become very big.

**Comment by HermannBjorgvin** [comment]
It's a multiplier. There's no other way to make things go faster than to either calculate more steps or calculate larger less accurate steps. But the number is basically a multiplier for all the force vectors so keep that in mind.

**Comment by Fabian42** [comment]
That's what I meant: It could just calculate more steps.

**Comment by HermannBjorgvin** [comment]
Fabian it's a multiplier on the vectors so that it's less precise but faster. You can't do endless calculations on an O(N ^ 2) algorithm like I'm using right now.

**Comment by Fabian42** [comment]
But if the CPU is nowhere near its limit, it can use more of it. Of course
that's limited, but up to 10x speed should be possible, I think.

**Comment by MuhsinFatih** [comment]
Cpu is at it's limit. Since the game calculates forces exerted on every particle by every particle, each particle you add doubles the amount of calculation needed. That is what Hermann meant when he said it's an O(n^2) algorithm. So 10X improvement, even if done, wouldnt help because its effect would only allow 1-2 more particles with same hardware. What will help is the Barnes-Hut implementation, which I guess will be done sometime in future, right Hermann? :D

**Comment by HermannBjorgvin** [comment]
@MuhsinFatih yeah, Barnes-Hut creates a quadtree that it iterates over instead of iterating over a list, it also has a greater amount of errors but that's adjustable and for a game simulator it's well acceptable, not sure when I'll finish it, this isn't really something I've been very focused on. @Fabian42 feel free to fork and make a commit
